### ISSUE TITLE
"Page not found" using plugin with "Booty Dark Admin Theme"

### ISSUE THREAD

**Issue by TheBuzzDee** [tompidev/booty-dark-admin-theme#3]
Hi,
I'm working on a little plugin, showing a simple ToDo-List in the admin area of bludit.
Have a look here: https://github.com/TheBuzzDee/bludit-todo

It works fine - except when the "Booty Dark Admin Theme" is installed.
(See issue on my plugin https://github.com/TheBuzzDee/bludit-todo/issues/2)

Calling my plugin uses the url "www.my-domain.com/admin/plugin/todo" - but as mentioned, it shows "Page not found".

btw, this plugin-example on the official bludit repository is producing the same error with "Booty Dark Admin Theme" enabled:  https://github.com/bludit/examples/tree/master/plugins/custom-controller-view-admin-panel

Could you please help me to find out, what part of the "Booty Dark Admin Theme" is causing my plugin not to work ?!
Thanks a lot an best regards,

TheBuzzDee

**Comment by s22-tech** [comment]
I decided to try this on my install to see if it worked, but unfortunately it doesn't fix the problem.  Adding 'configure-plugin' to adminSidebar() makes the link open the plugins admin page.

Marc

**Comment by s22-tech** [comment]
I got it to work.  I reverted 'configure-plugin' back to just 'plugin' and then on index.php I changed this section:

if (Sanitize::pathFile(PATH_ADMIN_VIEWS, $layout['view'] . '.php')) {
	include(PATH_ADMIN_VIEWS . $layout['view'] . '.php');
}
else {
	echo '<h1 class="text-center">' . $L->g('Page not found') . '</h1>';
	echo '<h2 class="text-center">' . $L->g('Choose a page from the sidebar.') . '</h2>';
}

to:

if (Sanitize::pathFile(PATH_ADMIN_VIEWS, $layout['view'] . '.php')) {
	include(PATH_ADMIN_VIEWS . $layout['view'] . '.php');
}
elseif ($layout['plugin'] && method_exists($layout['plugin'], 'adminView')) {
	echo $layout['plugin']->adminView();
}
else {
	echo '<h1 class="text-center">' . $L->g('Page not found') . '</h1>';
	echo '<h2 class="text-center">' . $L->g('Choose a page from the sidebar.') . '</h2>';
}

	Adding that elseif section adds the adminView() function which ToDo is calling.

Marc

**Comment by tompidev** [comment]
Thank you s22-tech!

I maked the [new release](https://github.com/tompidev/booty-dark-admin-theme/releases/tag/v1.1.5) based on your suggestion. 👍
